# gomdlint configuration for go-powers skill
# See: https://github.com/jamesainslie/gomdlint

flavor: gfm
severity_default: warning

backups:
  enabled: false

ignore:
  - "vendor/**"
  - "node_modules/**"
  - ".git/**"

rules:
  # Line length - 120 for prose, code blocks excluded
  MD013:
    enabled: true
    options:
      line_length: 120
      code_blocks: false
      tables: false

  # Duplicate headings - allow siblings with same name
  MD024:
    enabled: true
    options:
      siblings_only: true

  # Single H1 - disabled for skill files with frontmatter
  MD025:
    enabled: false

  # Fenced code language required
  MD040:
    enabled: true

  # Blanks around fences - disabled, false positives in gomdlint v0.1.2
  MD031:
    enabled: false

  # Blanks around lists - disabled, false positives in gomdlint v0.1.2
  MD032:
    enabled: false

  # Heading blank lines - disabled, false positives on YAML frontmatter in gomdlint v0.1.2
  MD022:
    enabled: false

  # Multiple consecutive blank lines
  MD012:
    enabled: true

  # Heading increment
  MD001:
    enabled: true

  # Trailing punctuation in headings - disabled for YAML frontmatter false positives
  MD026:
    enabled: false

  # Trailing spaces
  MD009:
    enabled: true

  # Hard tabs
  MD010:
    enabled: true

  # Single trailing newline
  MD047:
    enabled: true
